stages:
  - pre_release # a single stage allows test to run even if flake8 fails and makes it possible to get all the errors at once
  - release

# flake8:
#   tags:
#     - docker
#   image: python:3
#   stage: pre_release
#   script:
#     - pip install black flake8 flake8-black pep8-naming flake8-bugbear --constraint requirements-dev.txt
#     - flake8 -v shotmanager

doc:
  stage: pre_release
  tags:
    - docker
  image: python:3
  when: manual
  script:
    - pip install sphinx sphinx-rtd-theme
    - sphinx-build -b html docs docs/_build/html
    - rm -rf docs/_build/doctree
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_html"
    paths:
      - docs/_build
    expire_in: 1 week

zip:
  tags:
    - docker
  image: alpine
  stage: pre_release
  script:
    - cp CHANGELOG.md README.md LICENSE shotmanager/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - shotmanager
    expire_in: 1 week

# Note: you cannot extend this job with another only: variables job
# If you need that, you should rewrite and combine the rules
.only_version_tag:
  only:
    refs:
      # see inject_version.py
      - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(\-[0-9A-Za-z-]+)?(\+[0-9A-Za-z-]+)?$/

release:
  extends:
    - .only_version_tag
  dependencies:
    - zip
  tags:
    - docker
  image: python:3
  stage: release
  script:
    - pip install requests
    - python -m zipfile -c shotmanager-${CI_COMMIT_REF_NAME}.zip shotmanager/
    - python -m gitlab.release shotmanager-${CI_COMMIT_REF_NAME}.zip
  artifacts:
    paths:
      - shotmanager-${CI_COMMIT_REF_NAME}.zip

####################################################################################

